title = "HotDiML"
baseURL = "https://hotdiml.github.io/HotDiML2025"
theme = "ananke"
resourceDir = "../resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 0

[params.ananke.social.share]
networks = [
  "email",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "linkedin"
]

#Â [params.ananke.social.linkedin]
# username = "patrickkollitsch"



[[menu.main]]
  name = "Call for Papers"
  url = "/cfp"
  weight = 1

[[menu.main]]
  name = "Important Dates"
  url = "/dates"
  weight = 2

[[menu.main]]
  name = "Committee"
  url = "/committee"
  weight = 3

[[menu.main]]
  name = "Program"
  url = "/program"
  weight = 4

[[menu.main]]
  name = "Register"
  url = "/register"
  weight = 5


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true